"""Semillas extra para el corpus ACD — 185 textos adicionales.

Importar desde corpus.py:
    from core.semillas_200 import SEMILLAS_EXTRA
    SEMILLAS_ALL = SEMILLAS + SEMILLAS_EXTRA  # 200 total
"""

SEMILLAS_EXTRA = [
    # =====================================================================
    # BUSINESS / PILATES (40 textos)
    # =====================================================================

    # --- email_retencion (10) ---
    {"texto": "María, hace 4 semanas que no vienes. Tu monitora Laura dice que tu grupo de los miércoles pregunta por ti. Tenemos una plaza libre este miércoles a las 11:00. ¿Te reservo?", "efecto": {"persuasion": 0.82, "credibilidad": 0.75, "accion": 0.88, "empatia": 0.85}, "categoria": "email_retencion"},
    {"texto": "Hemos notado que no has venido últimamente. Queremos recordarte que tu bienestar es importante para nosotros. Esperamos verte pronto en nuestras instalaciones.", "efecto": {"persuasion": 0.15, "credibilidad": 0.12, "accion": 0.08, "empatia": 0.20}, "categoria": "email_retencion"},
    {"texto": "Pedro, llevas 22 días sin venir. En tus últimas 3 sesiones estabas trabajando la movilidad de cadera y habías progresado mucho. Si dejas pasar más de 30 días, ese progreso se pierde. ¿Retomamos este jueves?", "efecto": {"persuasion": 0.88, "credibilidad": 0.85, "accion": 0.82, "empatia": 0.70}, "categoria": "email_retencion"},
    {"texto": "¡ÚLTIMA OPORTUNIDAD! Si no renuevas tu plaza ESTA SEMANA la perderás para siempre. No dejes escapar esta ocasión irrepetible de cuidar tu salud.", "efecto": {"persuasion": 0.45, "credibilidad": 0.05, "accion": 0.55, "empatia": 0.0}, "categoria": "email_retencion"},
    {"texto": "Elena, sé que el cambio de horario laboral te complicó los martes. He abierto un grupo nuevo los jueves a las 19:30 que podría encajarte. Somos 4 por ahora, ambiente tranquilo. ¿Te apunto a una clase de prueba?", "efecto": {"persuasion": 0.85, "credibilidad": 0.80, "accion": 0.85, "empatia": 0.90}, "categoria": "email_retencion"},
    {"texto": "Estimado/a cliente, le informamos que su membresía se encuentra inactiva. Por favor, póngase en contacto con recepción para gestionar su reincorporación al programa de actividades.", "efecto": {"persuasion": 0.08, "credibilidad": 0.20, "accion": 0.10, "empatia": 0.02}, "categoria": "email_retencion"},
    {"texto": "Sofía, tu fisioterapeuta me ha pasado tu informe. Dice que el Pilates terapéutico 2 veces por semana es clave para tu recuperación de la hernia L4-L5. Tengo plaza los lunes y jueves a las 10:00 en grupo reducido (máx 4 personas). Primera sesión gratuita para que veas cómo trabajamos.", "efecto": {"persuasion": 0.90, "credibilidad": 0.92, "accion": 0.88, "empatia": 0.82}, "categoria": "email_retencion"},
    {"texto": "Te echamos de menos en el estudio. Vuelve cuando quieras, ¡te esperamos con los brazos abiertos! Tu salud es lo primero.", "efecto": {"persuasion": 0.20, "credibilidad": 0.10, "accion": 0.05, "empatia": 0.35}, "categoria": "email_retencion"},
    {"texto": "Javier, tu cuota de marzo está pagada pero no has venido ni una vez. Quedan 8 días. Tienes 12 clases disponibles. ¿Quieres que te reserve 2 esta semana para aprovechar lo que ya has pagado?", "efecto": {"persuasion": 0.80, "credibilidad": 0.90, "accion": 0.85, "empatia": 0.55}, "categoria": "email_retencion"},
    {"texto": "Recuerda que la falta de ejercicio tiene consecuencias graves. No esperes a que sea demasiado tarde. Millones de personas ya confían en el Pilates para su bienestar.", "efecto": {"persuasion": 0.40, "credibilidad": 0.08, "accion": 0.30, "empatia": 0.05}, "categoria": "email_retencion"},

    # --- confirmacion_cita (6) ---
    {"texto": "Tu cita de Pilates está confirmada: jueves 14 de marzo, 18:00h, Sala 2. Monitora: Laura. Llega 5 min antes. Cancela con 12h de antelación si no puedes. Responde OK para confirmar.", "efecto": {"persuasion": 0.35, "credibilidad": 0.90, "accion": 0.92, "empatia": 0.25}, "categoria": "confirmacion_cita"},
    {"texto": "Hola Ana, te confirmo tu sesión individual con Pablo el lunes 18 a las 9:30. Trae ropa cómoda y la toalla. Si necesitas cambiar hora, escríbeme antes del domingo.", "efecto": {"persuasion": 0.30, "credibilidad": 0.85, "accion": 0.88, "empatia": 0.50}, "categoria": "confirmacion_cita"},
    {"texto": "RECORDATORIO: Tienes clase mañana. Confirma asistencia.", "efecto": {"persuasion": 0.10, "credibilidad": 0.40, "accion": 0.45, "empatia": 0.02}, "categoria": "confirmacion_cita"},
    {"texto": "Lucía, mañana tienes Pilates suelo a las 10:00 con el grupo de Carmen. Esta semana trabajamos cadena posterior, así que ven con calcetines antideslizantes. Si llueve hay parking en la calle Lope de Vega.", "efecto": {"persuasion": 0.40, "credibilidad": 0.85, "accion": 0.80, "empatia": 0.60}, "categoria": "confirmacion_cita"},
    {"texto": "Su cita ha sido registrada en nuestro sistema. Le rogamos puntualidad. En caso de no poder asistir, comuníquelo con la debida antelación.", "efecto": {"persuasion": 0.05, "credibilidad": 0.30, "accion": 0.35, "empatia": 0.03}, "categoria": "confirmacion_cita"},
    {"texto": "Alberto, confirmo tu primera sesión de valoración este viernes 22 a las 17:00. Durará 45 min. Te haré unas preguntas sobre tu historial y haremos ejercicios básicos para ver tu nivel. No te preocupes, vamos a tu ritmo. ¿Alguna duda?", "efecto": {"persuasion": 0.50, "credibilidad": 0.88, "accion": 0.75, "empatia": 0.80}, "categoria": "confirmacion_cita"},

    # --- alerta_cobros (6) ---
    {"texto": "Laura, tu cuota de febrero (89€) sigue pendiente. El cargo se intentó el día 5 pero fue rechazado por tu banco. ¿Puedes actualizar la tarjeta antes del viernes? Así evitas el recargo de 5€.", "efecto": {"persuasion": 0.65, "credibilidad": 0.90, "accion": 0.85, "empatia": 0.45}, "categoria": "alerta_cobros"},
    {"texto": "Tienes un pago pendiente. Por favor, regulariza tu situación lo antes posible para seguir disfrutando de nuestros servicios.", "efecto": {"persuasion": 0.15, "credibilidad": 0.20, "accion": 0.25, "empatia": 0.05}, "categoria": "alerta_cobros"},
    {"texto": "Miguel, llevas 2 meses sin pagar (total: 238€). Entiendo que pueden haber sido meses difíciles. ¿Te parece si fraccionamos la deuda en 3 pagos? El primero de 80€ esta semana. Llámame y lo hablamos.", "efecto": {"persuasion": 0.75, "credibilidad": 0.85, "accion": 0.70, "empatia": 0.75}, "categoria": "alerta_cobros"},
    {"texto": "AVISO: Si no se regulariza el impago en 48 horas, su acceso será suspendido automáticamente y el caso se derivará a gestión de cobros.", "efecto": {"persuasion": 0.55, "credibilidad": 0.60, "accion": 0.70, "empatia": 0.0}, "categoria": "alerta_cobros"},
    {"texto": "Carmen, la domiciliación de marzo no se ha podido ejecutar. Son 119€ del plan Estándar. Puedes hacer transferencia a ES12 3456 7890 1234 5678 90 o pagar con tarjeta en recepción. ¿Qué te viene mejor?", "efecto": {"persuasion": 0.60, "credibilidad": 0.92, "accion": 0.88, "empatia": 0.50}, "categoria": "alerta_cobros"},
    {"texto": "Hola Raúl, te escribo porque hay un pequeño lío con tu cuota. El banco rechazó el cobro de 89€. A veces pasa por cambio de tarjeta o límite temporal. ¿Quieres que lo intentemos de nuevo o prefieres pasarte por el estudio?", "efecto": {"persuasion": 0.55, "credibilidad": 0.78, "accion": 0.72, "empatia": 0.70}, "categoria": "alerta_cobros"},

    # --- reporte_negocio (6) ---
    {"texto": "Resumen marzo 2026: 47 alumnos activos (+3 vs feb), tasa asistencia 78% (objetivo: 80%), 4 bajas, 7 altas. Ingresos: 5.430€. Clases con menor ocupación: viernes 20:00 (2/8) y sábado 12:00 (3/8). Recomendación: cerrar viernes 20:00 y abrir jueves 19:30.", "efecto": {"persuasion": 0.45, "credibilidad": 0.95, "accion": 0.70, "empatia": 0.15}, "categoria": "reporte_negocio"},
    {"texto": "El negocio va bien. Los clientes están contentos y las clases tienen buena ocupación. Seguiremos trabajando para mejorar.", "efecto": {"persuasion": 0.05, "credibilidad": 0.08, "accion": 0.02, "empatia": 0.10}, "categoria": "reporte_negocio"},
    {"texto": "Alerta: 5 clientes en riesgo de baja (sin asistir >14 días). Detalle: Laura P. (18 días, plan Premium), Miguel T. (15 días, Estándar), Sara G. (21 días, Básico), Pedro R. (16 días, Estándar), Ana M. (14 días, Premium). Valor mensual en riesgo: 586€. Acción sugerida: contacto personalizado esta semana.", "efecto": {"persuasion": 0.60, "credibilidad": 0.95, "accion": 0.88, "empatia": 0.30}, "categoria": "reporte_negocio"},
    {"texto": "Se han observado tendencias positivas en los indicadores clave de rendimiento del trimestre, con mejoras sustanciales en la satisfacción del cliente y la optimización de recursos.", "efecto": {"persuasion": 0.05, "credibilidad": 0.05, "accion": 0.02, "empatia": 0.03}, "categoria": "reporte_negocio"},
    {"texto": "Ratio instructor/alumno por clase (media marzo): Pilates suelo 1:6.2 (óptimo 1:8), Pilates máquinas 1:3.1 (óptimo 1:4), Individual 1:1. Coste hora instructor: 22€. Margen bruto por clase: suelo 68%, máquinas 52%, individual 45%. Las clases de suelo son las más rentables.", "efecto": {"persuasion": 0.40, "credibilidad": 0.95, "accion": 0.55, "empatia": 0.08}, "categoria": "reporte_negocio"},
    {"texto": "NPS marzo: 72 (bueno). Comentarios destacados: 'Me encanta el grupo de Laura' (x4), 'Horarios limitados por la tarde' (x3), 'Precio justo' (x2). Detractores (score <6): 2 clientes, ambos mencionan falta de parking.", "efecto": {"persuasion": 0.35, "credibilidad": 0.90, "accion": 0.50, "empatia": 0.40}, "categoria": "reporte_negocio"},

    # --- venta (6) ---
    {"texto": "Plan Rehabilitación: 2 sesiones individuales/semana (45 min) + 1 grupal. Valoración inicial con fisio incluida. 249€/mes. Duración mínima recomendada: 3 meses. Tu fisio puede enviarnos el informe por email. ¿Agendamos la valoración?", "efecto": {"persuasion": 0.78, "credibilidad": 0.88, "accion": 0.82, "empatia": 0.55}, "categoria": "venta"},
    {"texto": "Somos el mejor estudio de Pilates de la zona con los profesionales más cualificados y las instalaciones más modernas. ¡Ven a conocernos!", "efecto": {"persuasion": 0.12, "credibilidad": 0.05, "accion": 0.15, "empatia": 0.08}, "categoria": "venta"},
    {"texto": "Clase de prueba gratuita. Sin compromiso. Elige día y hora en nuestra web: estudiomovimiento.com/prueba. Grupos reducidos (máx 8). 3 niveles: iniciación, intermedio, avanzado. Pregunta por nuestro bono de 10 sesiones (ahorro del 15%).", "efecto": {"persuasion": 0.72, "credibilidad": 0.80, "accion": 0.90, "empatia": 0.30}, "categoria": "venta"},
    {"texto": "¡OFERTA IRRESISTIBLE! ¡SOLO HOY! ¡50% DE DESCUENTO! ¡NO TE LO PIERDAS! ¡PLAZAS LIMITADÍSIMAS!", "efecto": {"persuasion": 0.35, "credibilidad": 0.02, "accion": 0.40, "empatia": 0.0}, "categoria": "venta"},
    {"texto": "Rosa, después de tu clase de prueba me comentaste que te dolía la zona lumbar al estar sentada mucho rato. Con 2 sesiones semanales durante 6-8 semanas, el 80% de nuestros clientes con ese perfil notan mejora significativa. El plan Estándar (3 clases/semana, 119€) te permitiría avanzar más rápido. ¿Quieres probarlo 1 mes?", "efecto": {"persuasion": 0.88, "credibilidad": 0.85, "accion": 0.82, "empatia": 0.72}, "categoria": "venta"},
    {"texto": "Ofrecemos una amplia gama de servicios de bienestar integral diseñados para satisfacer las necesidades de nuestros distinguidos clientes en un entorno de excelencia.", "efecto": {"persuasion": 0.08, "credibilidad": 0.05, "accion": 0.05, "empatia": 0.05}, "categoria": "venta"},

    # --- whatsapp_personal (3) ---
    {"texto": "Hola Teresa, ¿cómo estás? Vi que el martes hiciste el ejercicio del puente con mucha más estabilidad que hace un mes. Se nota que estás siendo constante. ¡Sigue así!", "efecto": {"persuasion": 0.40, "credibilidad": 0.80, "accion": 0.15, "empatia": 0.88}, "categoria": "whatsapp_personal"},
    {"texto": "Buenos días. Le recordamos que puede consultar nuestros horarios actualizados en la web.", "efecto": {"persuasion": 0.05, "credibilidad": 0.25, "accion": 0.15, "empatia": 0.02}, "categoria": "whatsapp_personal"},
    {"texto": "Alicia, me enteré de lo de tu rodilla. No te preocupes, cuando te den el alta adaptamos los ejercicios. He trabajado con varias personas post-artroscopia y en 4-6 semanas suelen estar haciendo clase normal. Descansa y recupérate.", "efecto": {"persuasion": 0.45, "credibilidad": 0.82, "accion": 0.20, "empatia": 0.95}, "categoria": "whatsapp_personal"},

    # --- whatsapp_fidelizacion (3) ---
    {"texto": "¡Enhorabuena, David! Hoy cumples 6 meses con nosotros. Has venido 48 veces y tu monitora dice que has mejorado muchísimo en control pélvico. Como agradecimiento, tu próxima clase individual es por cuenta nuestra. ¿La quieres esta semana o la siguiente?", "efecto": {"persuasion": 0.65, "credibilidad": 0.90, "accion": 0.80, "empatia": 0.85}, "categoria": "whatsapp_fidelizacion"},
    {"texto": "Valoramos tu fidelidad. Como cliente VIP tienes acceso a beneficios exclusivos. Consulta las condiciones en recepción.", "efecto": {"persuasion": 0.12, "credibilidad": 0.15, "accion": 0.10, "empatia": 0.08}, "categoria": "whatsapp_fidelizacion"},
    {"texto": "Inés, quería contarte que en abril empezamos un taller de Pilates con aro los sábados (10:00-11:30). Como llevas más de un año y dominas bien los básicos, creo que te gustaría. Son 4 sesiones por 60€. Solo 6 plazas. ¿Te interesa?", "efecto": {"persuasion": 0.75, "credibilidad": 0.82, "accion": 0.78, "empatia": 0.70}, "categoria": "whatsapp_fidelizacion"},

    # =====================================================================
    # MARKETING (30 textos)
    # =====================================================================

    # --- marketing_agresivo (8) ---
    {"texto": "SOLO QUEDAN 2 PLAZAS. Si no te apuntas HOY, tendrás que esperar 3 MESES. Miles de personas ya han transformado su vida con nuestro método revolucionario. ¡No seas el último!", "efecto": {"persuasion": 0.50, "credibilidad": 0.05, "accion": 0.55, "empatia": 0.0}, "categoria": "marketing_agresivo"},
    {"texto": "Los expertos confirman que sin ejercicio regular tu cuerpo se deteriora un 2% cada año después de los 30. ¿Vas a permitir eso? Nuestro programa exclusivo, avalado por los mejores profesionales, revierte el daño en solo 8 semanas.", "efecto": {"persuasion": 0.55, "credibilidad": 0.10, "accion": 0.45, "empatia": 0.05}, "categoria": "marketing_agresivo"},
    {"texto": "TODO EL MUNDO lo está haciendo. ¿Tú todavía no? El Pilates es la tendencia número 1 en bienestar. No te quedes atrás. Únete al movimiento.", "efecto": {"persuasion": 0.40, "credibilidad": 0.03, "accion": 0.35, "empatia": 0.02}, "categoria": "marketing_agresivo"},
    {"texto": "Si no cuidas tu cuerpo ahora, lo pagarás caro después. Es así de simple. Nosotros tenemos LA solución. Garantizado o te devolvemos el dinero. Sin preguntas.", "efecto": {"persuasion": 0.45, "credibilidad": 0.08, "accion": 0.50, "empatia": 0.0}, "categoria": "marketing_agresivo"},
    {"texto": "Nuestras clientas pierden una media de 5 kilos en el primer mes y ganan una confianza que nunca habían tenido. Tú también puedes. Solo tienes que dar el primer paso. AHORA.", "efecto": {"persuasion": 0.48, "credibilidad": 0.07, "accion": 0.52, "empatia": 0.10}, "categoria": "marketing_agresivo"},
    {"texto": "¿Cansada de dolores? ¿De no dormir bien? ¿De sentirte agotada? El 99% de nuestros clientes resuelven TODOS estos problemas. ¿A qué esperas? Llama AHORA y obtén tu primera sesión GRATIS.", "efecto": {"persuasion": 0.50, "credibilidad": 0.04, "accion": 0.60, "empatia": 0.15}, "categoria": "marketing_agresivo"},
    {"texto": "ÚLTIMA HORA: Descubierto el secreto que los gimnasios no quieren que sepas. El Pilates es 3 veces más efectivo que el gym. Estudios lo demuestran. Infórmate antes de que sea tarde.", "efecto": {"persuasion": 0.42, "credibilidad": 0.03, "accion": 0.38, "empatia": 0.0}, "categoria": "marketing_agresivo"},
    {"texto": "O inviertes en tu salud o inviertes en médicos. Tú eliges. Nuestro centro es el único de la ciudad con el Método Certificado Internacional de Pilates Avanzado™.", "efecto": {"persuasion": 0.48, "credibilidad": 0.06, "accion": 0.42, "empatia": 0.0}, "categoria": "marketing_agresivo"},

    # --- marketing_honesto (6) ---
    {"texto": "En 2025, 127 personas se apuntaron a nuestro estudio. 89 siguen viniendo (70% retención). Las que se fueron, principalmente por: cambio de ciudad (12), precio (8), horarios (7), otros (11). Lo que más valoran las que se quedan: grupo reducido (92%), trato personal (88%), resultados (85%).", "efecto": {"persuasion": 0.72, "credibilidad": 0.95, "accion": 0.45, "empatia": 0.35}, "categoria": "marketing_honesto"},
    {"texto": "El Pilates no es milagroso. Necesitas mínimo 2 sesiones por semana durante 8-12 semanas para notar cambios reales. Te va a costar al principio. Pero si eres constante, el 82% de nuestros clientes reportan menos dolor de espalda a los 3 meses.", "efecto": {"persuasion": 0.80, "credibilidad": 0.90, "accion": 0.55, "empatia": 0.50}, "categoria": "marketing_honesto"},
    {"texto": "Nuestros instructores: Laura (12 años experiencia, formación Stott), Pablo (8 años, fisioterapeuta colegiado), Carmen (6 años, especialista embarazadas). Ratio máximo: 1 instructor por cada 8 alumnos en suelo, 4 en máquinas.", "efecto": {"persuasion": 0.55, "credibilidad": 0.92, "accion": 0.30, "empatia": 0.25}, "categoria": "marketing_honesto"},
    {"texto": "Precios claros: Básico 89€ (2/sem), Estándar 119€ (3/sem), Premium 169€ (ilimitado). Sin matrícula. Sin permanencia. Cancelación con 15 días de antelación. La clase de prueba es gratis y sin compromiso.", "efecto": {"persuasion": 0.68, "credibilidad": 0.95, "accion": 0.72, "empatia": 0.30}, "categoria": "marketing_honesto"},
    {"texto": "Lo que NO hacemos: no prometemos milagros, no usamos máquinas antiguas, no metemos 15 personas en una clase. Lo que SÍ hacemos: evaluación inicial personalizada, grupos de máximo 8, seguimiento mensual de tu progreso.", "efecto": {"persuasion": 0.75, "credibilidad": 0.88, "accion": 0.50, "empatia": 0.45}, "categoria": "marketing_honesto"},
    {"texto": "Llevamos 7 años en el barrio. 340 clientes han pasado por aquí. Nuestro Google tiene 4.8 estrellas con 156 reseñas. No somos perfectos, pero trabajamos cada día para mejorar. Ven a conocernos y decide tú.", "efecto": {"persuasion": 0.70, "credibilidad": 0.90, "accion": 0.60, "empatia": 0.50}, "categoria": "marketing_honesto"},

    # --- landing_page (6) ---
    {"texto": "Pilates en Salamanca. Grupos de 4-8 personas. 3 planes desde 89€/mes. Clase de prueba gratis. Lunes a sábado, 8:00 a 20:00. Calle Mayor 23, 1ºB. Reserva tu plaza: 923 456 789.", "efecto": {"persuasion": 0.62, "credibilidad": 0.85, "accion": 0.88, "empatia": 0.20}, "categoria": "landing_page"},
    {"texto": "Bienvenido a nuestro espacio de bienestar integral donde la excelencia se fusiona con la innovación para crear experiencias transformadoras que potencian tu mejor versión.", "efecto": {"persuasion": 0.08, "credibilidad": 0.03, "accion": 0.02, "empatia": 0.05}, "categoria": "landing_page"},
    {"texto": "¿Dolor de espalda? El 78% de nuestros clientes con dolor lumbar mejoraron en 8 semanas. Paso 1: Reserva tu valoración gratuita (30 min). Paso 2: Recibe tu plan personalizado. Paso 3: Empieza esta semana. Llama al 923 456 789 o reserva online.", "efecto": {"persuasion": 0.82, "credibilidad": 0.85, "accion": 0.92, "empatia": 0.55}, "categoria": "landing_page"},
    {"texto": "Únete a la revolución del bienestar. Porque tú lo mereces. Porque el cambio empieza hoy. Porque juntos somos más fuertes. Descubre el poder transformador del movimiento consciente.", "efecto": {"persuasion": 0.18, "credibilidad": 0.02, "accion": 0.10, "empatia": 0.12}, "categoria": "landing_page"},
    {"texto": "3 razones para elegirnos: 1) Instructores con más de 8 años de experiencia media. 2) Nunca más de 8 personas por clase. 3) Seguimiento mensual con fotos de tu evolución postural. Prueba gratis → estudiomovimiento.com/prueba", "efecto": {"persuasion": 0.75, "credibilidad": 0.82, "accion": 0.85, "empatia": 0.30}, "categoria": "landing_page"},
    {"texto": "Somos líderes en el sector del fitness premium con un enfoque holístico y disruptivo que redefine los estándares del bienestar personalizado en el siglo XXI.", "efecto": {"persuasion": 0.05, "credibilidad": 0.02, "accion": 0.02, "empatia": 0.0}, "categoria": "landing_page"},

    # --- email_frio (5) ---
    {"texto": "Hola Dra. García, soy Pablo del estudio de Pilates de la calle Mayor. He visto que su clínica de fisioterapia está a 200 metros de nosotros. Tenemos 12 clientes que vienen derivados de fisios. ¿Le interesaría que colaboremos? Puedo acercarme con un café a contarle cómo funciona.", "efecto": {"persuasion": 0.78, "credibilidad": 0.80, "accion": 0.72, "empatia": 0.55}, "categoria": "email_frio"},
    {"texto": "Estimado señor/señora, nos dirigimos a usted para presentarle nuestra empresa líder en el sector del bienestar con el fin de explorar posibles sinergias que redunden en beneficio mutuo.", "efecto": {"persuasion": 0.05, "credibilidad": 0.08, "accion": 0.05, "empatia": 0.0}, "categoria": "email_frio"},
    {"texto": "Sr. Martínez, vi su post en LinkedIn sobre la importancia del bienestar laboral. En nuestro estudio ofrecemos clases de Pilates corporativo in-company (mínimo 6 empleados). Precio: 15€/persona/sesión. 3 empresas del polígono ya lo hacen. ¿Le envío una propuesta para su equipo?", "efecto": {"persuasion": 0.80, "credibilidad": 0.85, "accion": 0.78, "empatia": 0.40}, "categoria": "email_frio"},
    {"texto": "¡¡¡INCREÍBLE OPORTUNIDAD DE NEGOCIO!!! ¡¡¡GANE DINERO DESDE CASA CON NUESTRO PROGRAMA DE AFILIADOS DE PILATES!!! ¡¡¡SIN INVERSIÓN INICIAL!!!", "efecto": {"persuasion": 0.15, "credibilidad": 0.0, "accion": 0.20, "empatia": 0.0}, "categoria": "email_frio"},
    {"texto": "Hola Marta, coincidimos en el congreso de fisioterapia de Madrid el mes pasado. Te comenté que hacemos Pilates terapéutico con derivación directa de fisios. Te paso nuestra ficha de derivación y el protocolo que seguimos. Si quieres, agendamos una videollamada de 15 min para contarte cómo lo hacemos con los otros 4 fisios que colaboran con nosotros.", "efecto": {"persuasion": 0.82, "credibilidad": 0.88, "accion": 0.75, "empatia": 0.60}, "categoria": "email_frio"},

    # --- social_media (5) ---
    {"texto": "Hoy en clase, Carmen (68 años) ha hecho su primera plancha completa de 30 segundos. Lleva 4 meses con nosotros. Cuando empezó no podía mantener 5 segundos. La cara de orgullo no tiene precio. Esto es lo que nos motiva cada día. #pilates #nunca_es_tarde", "efecto": {"persuasion": 0.72, "credibilidad": 0.82, "accion": 0.30, "empatia": 0.90}, "categoria": "social_media"},
    {"texto": "¡¡Buenos días!! ¡¡Nuevo día, nueva oportunidad!! ¡¡Ven a hacer Pilates!! 💪💪💪 #fitness #salud #bienestar #pilates #healthylife #motivation #love #instagood", "efecto": {"persuasion": 0.10, "credibilidad": 0.02, "accion": 0.12, "empatia": 0.05}, "categoria": "social_media"},
    {"texto": "Dato: El 85% de las personas que dejan el gimnasio en enero siguen pagando la cuota hasta marzo. En Pilates nuestra tasa de abandono en enero es del 8%. ¿La diferencia? Grupos pequeños donde alguien nota si no vienes. Eso no lo da un gym.", "efecto": {"persuasion": 0.78, "credibilidad": 0.82, "accion": 0.35, "empatia": 0.45}, "categoria": "social_media"},
    {"texto": "Pilates es vida. Pilates es amor. Pilates es todo. #blessed #grateful #pilateseveryday", "efecto": {"persuasion": 0.05, "credibilidad": 0.0, "accion": 0.05, "empatia": 0.08}, "categoria": "social_media"},
    {"texto": "Antes y después de 6 meses de Pilates de Roberto (con su permiso). Foto 1: cifosis dorsal marcada, hombros adelantados. Foto 2: columna mucho más alineada, hombros abiertos. 0 cirugías, 0 medicamentos. 2 clases por semana durante 6 meses. Resultados reales, no photoshop.", "efecto": {"persuasion": 0.80, "credibilidad": 0.88, "accion": 0.40, "empatia": 0.55}, "categoria": "social_media"},

    # =====================================================================
    # EDUCACION (25 textos)
    # =====================================================================

    # --- educativo_bueno (8) ---
    {"texto": "La respiración lateral costal es la base del Pilates. Así se hace: 1) Pon las manos en las costillas laterales. 2) Inhala por la nariz expandiendo costillas hacia los lados (no el pecho hacia arriba). 3) Exhala por la boca cerrando costillas. 4) Mantén el abdomen activo en ambas fases. Practica 10 respiraciones antes de cada clase.", "efecto": {"persuasion": 0.35, "credibilidad": 0.88, "accion": 0.82, "empatia": 0.40}, "categoria": "educativo_bueno"},
    {"texto": "Diferencia entre Pilates suelo y máquinas: En suelo trabajas contra la gravedad usando tu propio peso. En máquinas (Reformer) los muelles ofrecen resistencia variable: más muelles = más asistencia en algunos ejercicios y más resistencia en otros. Para principiantes, el Reformer suele ser más accesible porque los muelles ayudan.", "efecto": {"persuasion": 0.30, "credibilidad": 0.85, "accion": 0.25, "empatia": 0.35}, "categoria": "educativo_bueno"},
    {"texto": "Por qué duele la espalda baja al estar sentado: el psoas ilíaco se acorta, tirando de las vértebras lumbares hacia delante (hiperlordosis). Esto comprime los discos L4-L5 y L5-S1. En Pilates estiramos el psoas con el ejercicio 'cisne' y fortalecemos el transverso abdominal que estabiliza la zona. 2 meses de práctica regular suelen reducir el dolor significativamente.", "efecto": {"persuasion": 0.45, "credibilidad": 0.90, "accion": 0.35, "empatia": 0.50}, "categoria": "educativo_bueno"},
    {"texto": "Los 6 principios de Pilates de Joseph Pilates: 1) Concentración: atención plena en cada movimiento. 2) Control: cada movimiento es deliberado. 3) Centro: todo nace del core. 4) Fluidez: movimientos continuos, sin parones. 5) Precisión: calidad sobre cantidad. 6) Respiración: coordinada con el movimiento.", "efecto": {"persuasion": 0.30, "credibilidad": 0.85, "accion": 0.20, "empatia": 0.25}, "categoria": "educativo_bueno"},
    {"texto": "Frecuencia óptima de Pilates según objetivo: Mantenimiento: 1-2 sesiones/semana. Mejora activa: 3 sesiones/semana. Rehabilitación: 2-3 sesiones/semana + ejercicios en casa diarios (15 min). Más de 4 sesiones/semana no aporta beneficio adicional y puede causar sobreentrenamiento. Descanso mínimo entre sesiones: 24h.", "efecto": {"persuasion": 0.40, "credibilidad": 0.88, "accion": 0.55, "empatia": 0.30}, "categoria": "educativo_bueno"},
    {"texto": "Cómo saber si estás activando bien el transverso: Túmbate boca arriba con rodillas flexionadas. Pon los dedos 2 cm por debajo del ombligo, hacia los lados. Tose suavemente: esa contracción que notas bajo los dedos es el transverso. Ahora intenta reproducir esa contracción suave (un 30% de tu máximo) mientras respiras con normalidad. Si puedes hablar mientras lo haces, vas bien.", "efecto": {"persuasion": 0.30, "credibilidad": 0.90, "accion": 0.85, "empatia": 0.45}, "categoria": "educativo_bueno"},
    {"texto": "Error común en el roll-up: tirar del cuello con las manos. Lo correcto es articular la columna vértebra a vértebra, usando los abdominales para subir. Si no llegas arriba, dobla ligeramente las rodillas. Es mejor hacer medio roll-up con buena técnica que uno completo tirando del cuello. Tu instructor debería corregirte si te ve forzar.", "efecto": {"persuasion": 0.35, "credibilidad": 0.88, "accion": 0.60, "empatia": 0.50}, "categoria": "educativo_bueno"},
    {"texto": "Pilates durante el embarazo: seguro a partir de la semana 12 con instructor especializado. Beneficios demostrados: menor incidencia de dolor lumbar (reducción del 65% según estudio de la Universidad de Sevilla, 2023), mejor recuperación posparto, menor tasa de cesárea en mujeres activas. Contraindicaciones: placenta previa, hipertensión gestacional, riesgo de parto prematuro. Siempre con autorización del ginecólogo.", "efecto": {"persuasion": 0.50, "credibilidad": 0.92, "accion": 0.40, "empatia": 0.55}, "categoria": "educativo_bueno"},

    # --- educativo_malo (7) ---
    {"texto": "El Pilates es muy bueno para la salud. Mejora muchas cosas del cuerpo y te hace sentir mejor. Es importante hacer ejercicio regularmente para estar sano.", "efecto": {"persuasion": 0.08, "credibilidad": 0.05, "accion": 0.05, "empatia": 0.10}, "categoria": "educativo_malo"},
    {"texto": "Los músculos trabajan de forma sinérgica en una cadena cinética que optimiza el patrón neuromuscular mediante la activación progresiva de las unidades motoras en un continuum de intensidad variable.", "efecto": {"persuasion": 0.10, "credibilidad": 0.15, "accion": 0.02, "empatia": 0.0}, "categoria": "educativo_malo"},
    {"texto": "Es fundamental comprender que el movimiento correcto es esencial para evitar lesiones y maximizar los beneficios del ejercicio. La técnica adecuada marca la diferencia entre un entrenamiento efectivo y uno que no lo es.", "efecto": {"persuasion": 0.08, "credibilidad": 0.10, "accion": 0.05, "empatia": 0.05}, "categoria": "educativo_malo"},
    {"texto": "El core es muy importante. Si tienes un core fuerte, todo va mejor. Hay que trabajar el core todos los días. El Pilates trabaja el core. Por eso el Pilates es bueno.", "efecto": {"persuasion": 0.12, "credibilidad": 0.08, "accion": 0.05, "empatia": 0.08}, "categoria": "educativo_malo"},
    {"texto": "La biomecánica funcional del aparato locomotor se ve potenciada mediante la implementación de protocolos de entrenamiento basados en la evidencia que incorporan paradigmas de control motor neurofisiológico.", "efecto": {"persuasion": 0.05, "credibilidad": 0.12, "accion": 0.0, "empatia": 0.0}, "categoria": "educativo_malo"},
    {"texto": "Básicamente, lo que hay que hacer es moverse bien. Si te mueves bien, no te lesionas. Y si no te lesionas, puedes seguir moviéndote. Es así de simple, la verdad.", "efecto": {"persuasion": 0.10, "credibilidad": 0.05, "accion": 0.08, "empatia": 0.12}, "categoria": "educativo_malo"},
    {"texto": "Se ha demostrado científicamente que el ejercicio es beneficioso. Diversos estudios confirman los efectos positivos de la actividad física en la salud general. Los expertos recomiendan realizar ejercicio de forma regular.", "efecto": {"persuasion": 0.12, "credibilidad": 0.15, "accion": 0.05, "empatia": 0.03}, "categoria": "educativo_malo"},

    # --- tutorial (5) ---
    {"texto": "Cómo hacer la plancha correctamente: 1) Apoya antebrazos y puntas de los pies. 2) Alinea hombros sobre codos. 3) Activa abdomen (ombligo hacia columna). 4) No dejes caer caderas ni las subas en pico. 5) Mira al suelo, cuello largo. 6) Mantén 20-30 seg. 7) Descansa 15 seg. 8) Repite 3 veces. Si tiemblas está bien, si duele la espalda baja, sube caderas ligeramente.", "efecto": {"persuasion": 0.30, "credibilidad": 0.88, "accion": 0.95, "empatia": 0.35}, "categoria": "tutorial"},
    {"texto": "Estiramiento del psoas en casa: Rodilla derecha en el suelo (pon una toalla debajo), pie izquierdo adelantado en ángulo de 90°. Empuja caderas hacia delante suavemente hasta notar estiramiento en la ingle derecha. Mantén 30 seg. Respira normal. Cambia de lado. Repite 2 veces por lado. Hazlo después de estar sentado mucho rato.", "efecto": {"persuasion": 0.25, "credibilidad": 0.85, "accion": 0.92, "empatia": 0.40}, "categoria": "tutorial"},
    {"texto": "Ejercicio de movilidad de columna (gato-vaca): A cuatro patas, manos bajo hombros, rodillas bajo caderas. Al exhalar: redondea la espalda hacia el techo, mete barbilla. Al inhalar: deja caer el abdomen, mira al frente. Hazlo lento, 8-10 repeticiones. Ideal para primera hora de la mañana o entre horas de oficina.", "efecto": {"persuasion": 0.25, "credibilidad": 0.85, "accion": 0.90, "empatia": 0.38}, "categoria": "tutorial"},
    {"texto": "Para hacer el ejercicio, simplemente tienes que seguir los pasos correctamente y prestar atención a tu cuerpo. Es importante que lo hagas bien para obtener resultados.", "efecto": {"persuasion": 0.05, "credibilidad": 0.05, "accion": 0.08, "empatia": 0.05}, "categoria": "tutorial"},
    {"texto": "Rutina de 15 min para dolor de espalda (hazla 5 días/semana): Min 0-3: gato-vaca (10 rep). Min 3-6: puente de glúteos (3x12, aguantando arriba 3 seg). Min 6-9: estiramiento psoas (30 seg/lado x2). Min 9-12: dead bug (3x8 por lado, exhala al estirar). Min 12-15: posición fetal 1 min + respiración profunda. Progresión: semana 1-2 sin peso, semana 3-4 con banda elástica en puente.", "efecto": {"persuasion": 0.40, "credibilidad": 0.90, "accion": 0.95, "empatia": 0.42}, "categoria": "tutorial"},

    # --- motivacional (5) ---
    {"texto": "Marta empezó con nosotros hace un año sin poder tocarse los pies. Ayer hizo una clase avanzada completa. No fue fácil: hubo semanas que no quería venir. Pero vino. 96 clases después, su espalda no le duele, duerme mejor y corre detrás de sus hijos sin quedarse sin aire. Esa es la victoria real.", "efecto": {"persuasion": 0.75, "credibilidad": 0.85, "accion": 0.40, "empatia": 0.88}, "categoria": "motivacional"},
    {"texto": "¡Tú puedes! ¡Cree en ti! ¡El límite está en tu mente! ¡Cada día es una oportunidad! ¡No te rindas nunca! ¡Eres más fuerte de lo que crees!", "efecto": {"persuasion": 0.15, "credibilidad": 0.02, "accion": 0.10, "empatia": 0.12}, "categoria": "motivacional"},
    {"texto": "El progreso en Pilates no es lineal. La semana 3 suele ser la más difícil: tu cuerpo sabe que es diferente pero todavía no nota resultados. La mayoría que abandona lo hace aquí. Si llegas a la semana 6, ya no lo dejas. Lo sé porque llevo 12 años viendo el mismo patrón.", "efecto": {"persuasion": 0.72, "credibilidad": 0.82, "accion": 0.45, "empatia": 0.65}, "categoria": "motivacional"},
    {"texto": "Recuerda: no se trata de ser perfecto, se trata de ser constante. Joseph Pilates decía: 'En 10 sesiones sentirás la diferencia, en 20 la verás y en 30 tendrás un cuerpo nuevo'. Lleva razón, pero yo añado: en la sesión 1 ya estás haciendo más que el que no empieza.", "efecto": {"persuasion": 0.65, "credibilidad": 0.70, "accion": 0.35, "empatia": 0.60}, "categoria": "motivacional"},
    {"texto": "Cada obstáculo es una oportunidad disfrazada. El camino hacia el bienestar comienza con un solo paso. Abraza el cambio y transforma tu vida. El momento es ahora.", "efecto": {"persuasion": 0.15, "credibilidad": 0.03, "accion": 0.12, "empatia": 0.10}, "categoria": "motivacional"},

    # =====================================================================
    # COMUNICACION PROFESIONAL (30 textos)
    # =====================================================================

    # --- reporte_ejecutivo (8) ---
    {"texto": "Resumen ejecutivo Q1 2026: Revenue 16.200€ (+8% vs Q4). EBITDA 4.860€ (margen 30%). Clientes activos: 52 (+6). Churn rate: 7.8% (target <10%). NPS: 72. Riesgos: 3 instructores al 85% capacidad, necesitamos contratar en Q2 si crecimiento >5%. Decisión requerida: aprobar búsqueda de instructor freelance (coste estimado: 22€/h, 10h/semana).", "efecto": {"persuasion": 0.55, "credibilidad": 0.95, "accion": 0.80, "empatia": 0.10}, "categoria": "reporte_ejecutivo"},
    {"texto": "El rendimiento del trimestre ha sido satisfactorio, con resultados alineados con las expectativas y un desempeño general acorde a los estándares del sector.", "efecto": {"persuasion": 0.05, "credibilidad": 0.05, "accion": 0.02, "empatia": 0.03}, "categoria": "reporte_ejecutivo"},
    {"texto": "Análisis de rentabilidad por servicio (marzo): Pilates suelo: 68% margen, 120 sesiones. Pilates máquinas: 52% margen, 80 sesiones. Individual: 45% margen, 40 sesiones. Bono 10 sesiones: 55% margen, 15 bonos vendidos. Recomendación: incentivar bonos (mayor compromiso del cliente + margen superior a individual) y limitar individuales a 10 sesiones/semana para no saturar a instructores.", "efecto": {"persuasion": 0.55, "credibilidad": 0.95, "accion": 0.72, "empatia": 0.08}, "categoria": "reporte_ejecutivo"},
    {"texto": "En línea con nuestra visión estratégica de posicionamiento competitivo, hemos implementado iniciativas transversales que potencian sinergias operativas y generan valor añadido sostenible.", "efecto": {"persuasion": 0.03, "credibilidad": 0.02, "accion": 0.0, "empatia": 0.0}, "categoria": "reporte_ejecutivo"},
    {"texto": "Informe de incidencias marzo: 2 quejas formales (ambas por temperatura de sala, resueltas con termostato nuevo), 1 baja médica instructora (Carmen, 10 días, cubierta por Pablo), 0 accidentes, 0 reclamaciones en Consumo. Tiempo medio respuesta a incidencias: 4h (target: 24h).", "efecto": {"persuasion": 0.30, "credibilidad": 0.92, "accion": 0.45, "empatia": 0.20}, "categoria": "reporte_ejecutivo"},
    {"texto": "Los resultados evidencian una tendencia positiva que refleja el compromiso de la organización con la excelencia operativa y la mejora continua de los procesos internos.", "efecto": {"persuasion": 0.05, "credibilidad": 0.03, "accion": 0.0, "empatia": 0.02}, "categoria": "reporte_ejecutivo"},
    {"texto": "Pipeline ventas abril: 8 leads cualificados (5 por recomendación, 2 Instagram, 1 web). De los 8: 3 han agendado prueba gratuita, 2 pidieron info de precios, 3 sin responder al segundo contacto. Valor potencial si convierten todos: 784€/mes. Conversión histórica de lead a cliente: 35%. Estimación realista: 2-3 altas nuevas.", "efecto": {"persuasion": 0.45, "credibilidad": 0.92, "accion": 0.60, "empatia": 0.12}, "categoria": "reporte_ejecutivo"},
    {"texto": "Estado del equipo: Laura (100% capacidad, satisfecha, solicita formación en Pilates aéreo), Pablo (85% capacidad, contento pero pide revisión salarial en junio), Carmen (vuelta de baja, bien, retoma al 60% primera semana). Riesgo: Pablo tiene oferta de otro estudio. Recomendación: adelantar conversación salarial a abril.", "efecto": {"persuasion": 0.60, "credibilidad": 0.90, "accion": 0.72, "empatia": 0.50}, "categoria": "reporte_ejecutivo"},

    # --- propuesta_negocio (6) ---
    {"texto": "Propuesta de colaboración Estudio Movimiento × Clínica FisioSalud: Derivación bilateral de pacientes/clientes. Protocolo: el fisio envía ficha con diagnóstico, nosotros adaptamos ejercicios y reportamos progreso mensual. Beneficio para la clínica: fidelización paciente + comisión 10% primer trimestre del cliente derivado. Beneficio para nosotros: clientes cualificados con necesidad real. Piloto: 3 meses, revisable.", "efecto": {"persuasion": 0.78, "credibilidad": 0.88, "accion": 0.72, "empatia": 0.35}, "categoria": "propuesta_negocio"},
    {"texto": "Le proponemos una alianza estratégica que genere sinergias win-win y potencie el posicionamiento de ambas marcas en el ecosistema del bienestar.", "efecto": {"persuasion": 0.08, "credibilidad": 0.03, "accion": 0.05, "empatia": 0.02}, "categoria": "propuesta_negocio"},
    {"texto": "Propuesta Pilates corporativo para Empresa ABC (45 empleados): 1 sesión semanal de 50 min en sus oficinas (sala de reuniones despejada). Grupo de 8-12 personas. Coste: 180€/sesión (15€/persona con 12). Incluye: esterillas, material, instructor titulado. Duración contrato: 6 meses renovables. Beneficios medidos: reducción absentismo 12% (dato de nuestros 3 clientes corporativos actuales).", "efecto": {"persuasion": 0.82, "credibilidad": 0.90, "accion": 0.75, "empatia": 0.30}, "categoria": "propuesta_negocio"},
    {"texto": "Nuestra propuesta de valor se fundamenta en pilares sólidos de innovación y excelencia que nos posicionan como referentes en el mercado del bienestar integral.", "efecto": {"persuasion": 0.05, "credibilidad": 0.02, "accion": 0.02, "empatia": 0.0}, "categoria": "propuesta_negocio"},
    {"texto": "Plan de expansión: abrir segundo estudio en zona norte. Inversión estimada: 35.000€ (reforma 15K, equipamiento 12K, marketing lanzamiento 3K, capital trabajo 5K). Break-even: mes 8 con 25 clientes. ROI proyectado a 2 años: 140%. Financiación: 20K fondos propios + 15K préstamo ICO. Riesgo principal: canibalización del estudio actual (mitigado: 4 km distancia).", "efecto": {"persuasion": 0.65, "credibilidad": 0.88, "accion": 0.62, "empatia": 0.10}, "categoria": "propuesta_negocio"},
    {"texto": "Queremos explorar oportunidades de colaboración que permitan maximizar el impacto de nuestras respectivas propuestas de valor en el mercado target.", "efecto": {"persuasion": 0.05, "credibilidad": 0.03, "accion": 0.05, "empatia": 0.0}, "categoria": "propuesta_negocio"},

    # --- feedback_empleado (8) ---
    {"texto": "Laura, quería hablarte de tus clases del último mes. He observado 3 sesiones tuyas y los clientes están encantados (NPS de tus grupos: 82). Punto fuerte: tu capacidad de adaptar ejercicios al momento. Área de mejora: a veces adelantas el ritmo y los principiantes se pierden. ¿Te parece si en los grupos mixtos dedicas los primeros 5 minutos a los básicos y luego ofreces progresiones?", "efecto": {"persuasion": 0.55, "credibilidad": 0.90, "accion": 0.72, "empatia": 0.75}, "categoria": "feedback_empleado"},
    {"texto": "Tu rendimiento es adecuado y se alinea con los estándares esperados. Sigue así.", "efecto": {"persuasion": 0.05, "credibilidad": 0.10, "accion": 0.02, "empatia": 0.05}, "categoria": "feedback_empleado"},
    {"texto": "Pablo, tres clientes me han dicho esta semana que tus clases de máquinas son las mejores que han tenido. Concretamente, Sara dijo que por primera vez entiende para qué sirve cada muelle. Eso es mérito tuyo. Me gustaría que grabaras un vídeo corto explicando tu método para que Carmen pueda usarlo como referencia.", "efecto": {"persuasion": 0.50, "credibilidad": 0.88, "accion": 0.65, "empatia": 0.80}, "categoria": "feedback_empleado"},
    {"texto": "Hay que mejorar en varios aspectos. La puntualidad es importante. También la comunicación con los clientes. Y el orden del material después de clase. En general, bien pero hay margen de mejora.", "efecto": {"persuasion": 0.12, "credibilidad": 0.20, "accion": 0.15, "empatia": 0.08}, "categoria": "feedback_empleado"},
    {"texto": "Carmen, bienvenida de vuelta. Antes de que retomes al 100%, quiero que sepas: Pablo cubrió tus clases y los clientes te echaron de menos (4 me preguntaron cuándo volvías). Para esta primera semana te he puesto solo 3 clases de suelo (nada de máquinas). La semana que viene subimos a 5. ¿Cómo te encuentras? ¿Necesitas algo?", "efecto": {"persuasion": 0.35, "credibilidad": 0.85, "accion": 0.50, "empatia": 0.92}, "categoria": "feedback_empleado"},
    {"texto": "Se considera necesario implementar mejoras en el desempeño profesional conforme a los indicadores de calidad establecidos en el manual de procedimientos.", "efecto": {"persuasion": 0.05, "credibilidad": 0.08, "accion": 0.08, "empatia": 0.0}, "categoria": "feedback_empleado"},
    {"texto": "Pablo, tenemos que hablar de los retrasos. En marzo has llegado tarde 4 veces (días 3, 11, 18 y 25, siempre al grupo de 9:00). Los clientes esperan en la puerta. Entiendo que madrugar es duro, pero es tu compromiso. ¿Qué está pasando? ¿Hay algo que pueda hacer para ayudarte? Si el horario no te funciona, podemos explorar un cambio.", "efecto": {"persuasion": 0.60, "credibilidad": 0.90, "accion": 0.65, "empatia": 0.65}, "categoria": "feedback_empleado"},
    {"texto": "Tu trabajo es bueno. Los clientes te quieren. Sigue esforzándote. Buen trabajo en general.", "efecto": {"persuasion": 0.08, "credibilidad": 0.08, "accion": 0.02, "empatia": 0.15}, "categoria": "feedback_empleado"},

    # --- comunicado_interno (8) ---
    {"texto": "Equipo, a partir del 1 de abril cambiamos el horario de limpieza: de 14:00-15:00 a 7:00-8:00. Esto significa que la sala estará lista desde las 8:00 (ahora es desde las 8:30). Los que dais clase a las 8:00, tendréis que entrar por la puerta lateral esa primera media hora. Pablo, ¿puedes encargarte de abrir?", "efecto": {"persuasion": 0.30, "credibilidad": 0.85, "accion": 0.78, "empatia": 0.30}, "categoria": "comunicado_interno"},
    {"texto": "Se comunica que se procederá a la implementación de cambios operativos que optimizarán los flujos de trabajo internos en aras de la mejora continua.", "efecto": {"persuasion": 0.03, "credibilidad": 0.05, "accion": 0.02, "empatia": 0.0}, "categoria": "comunicado_interno"},
    {"texto": "Recordatorio: el martes 2 de abril tenemos la reunión trimestral (10:00-11:30, sala grande). Orden del día: 1) Resultados Q1 (15 min, yo). 2) Nuevos horarios abril (10 min, Laura). 3) Protocolo nuevos alumnos (15 min, Pablo). 4) Dudas/propuestas (30 min, todos). Traed ideas para la jornada de puertas abiertas de mayo.", "efecto": {"persuasion": 0.25, "credibilidad": 0.88, "accion": 0.82, "empatia": 0.25}, "categoria": "comunicado_interno"},
    {"texto": "Importante: el seguro de responsabilidad civil se renueva el 15 de abril. Necesito que Laura y Carmen me envíen antes del 10 la copia de su titulación actualizada (la de Pablo ya la tengo). Sin eso, la aseguradora no cubre las clases.", "efecto": {"persuasion": 0.50, "credibilidad": 0.88, "accion": 0.90, "empatia": 0.20}, "categoria": "comunicado_interno"},
    {"texto": "Se pone en conocimiento del equipo que se están evaluando las opciones disponibles para la optimización de los procedimientos vigentes.", "efecto": {"persuasion": 0.02, "credibilidad": 0.03, "accion": 0.0, "empatia": 0.0}, "categoria": "comunicado_interno"},
    {"texto": "Equipo, ayer una clienta (Teresa M.) resbaló en la sala 2 porque el suelo estaba mojado después de limpiar. No se hizo daño, pero casi. A partir de hoy: 1) El último en usar cada sala pasa la mopa seca. 2) Señal de suelo mojado siempre que se friegue. 3) Cualquier incidencia, fotos + me escribís inmediatamente. ¿Alguna duda?", "efecto": {"persuasion": 0.55, "credibilidad": 0.90, "accion": 0.92, "empatia": 0.35}, "categoria": "comunicado_interno"},
    {"texto": "Os cuento: he conseguido que una marca de ropa deportiva local (MoveFit) nos patrocine camisetas para el equipo. Son bonitas y gratis. Solo piden que las llevemos en las clases y subamos alguna foto a redes. Laura, ¿puedes elegir talla para todos? Las traen el lunes.", "efecto": {"persuasion": 0.40, "credibilidad": 0.82, "accion": 0.68, "empatia": 0.50}, "categoria": "comunicado_interno"},
    {"texto": "Aviso: cliente VIP (Sra. Rodríguez, plan Premium) ha pedido cambiar sus 3 sesiones de lunes-miércoles-viernes a martes-jueves-sábado a partir de la próxima semana. Lleva 2 años, paga puntual, nunca ha dado problemas. Pablo, ella prefiere tus clases. ¿Puedes acomodarla en tus grupos de martes y jueves? El sábado la cojo yo.", "efecto": {"persuasion": 0.45, "credibilidad": 0.90, "accion": 0.75, "empatia": 0.55}, "categoria": "comunicado_interno"},

    # =====================================================================
    # VENTAS / PERSUASION (30 textos)
    # =====================================================================

    # --- pitch_inversor (8) ---
    {"texto": "Estudio Movimiento genera 65.000€/año con 1 local de 120m² y 3 instructores. Margen EBITDA: 30%. El modelo es replicable: segundo local en zona norte costaría 35K y alcanzaría break-even en 8 meses. Buscamos 50K para abrir 2 locales en 2027. ROI proyectado: 25% anual. Exit: venta a cadena (3 ofertas recibidas de franquicias en 2025).", "efecto": {"persuasion": 0.80, "credibilidad": 0.90, "accion": 0.70, "empatia": 0.10}, "categoria": "pitch_inversor"},
    {"texto": "Nuestra visión es revolucionar el sector del bienestar con una propuesta disruptiva que escala globalmente aprovechando las megatendencias de salud y wellness.", "efecto": {"persuasion": 0.15, "credibilidad": 0.03, "accion": 0.08, "empatia": 0.0}, "categoria": "pitch_inversor"},
    {"texto": "Problema: el 60% de personas con dolor de espalda crónico no hacen ejercicio porque los gimnasios les intimidan. Solución: estudios de Pilates con grupos pequeños y seguimiento personalizado. Mercado: 8M de personas con dolor crónico en España. Nuestro modelo: unit economics probados en 1 local (LTV cliente: 1.428€, CAC: 45€, ratio 32:1). Pedimos 150K para abrir 5 locales en 3 ciudades.", "efecto": {"persuasion": 0.85, "credibilidad": 0.88, "accion": 0.65, "empatia": 0.35}, "categoria": "pitch_inversor"},
    {"texto": "Somos el Uber del Pilates. Vamos a ser el próximo unicornio del wellness. El mercado es enorme y nosotros tenemos el equipo para capturarlo.", "efecto": {"persuasion": 0.25, "credibilidad": 0.05, "accion": 0.15, "empatia": 0.0}, "categoria": "pitch_inversor"},
    {"texto": "Traction: 52 clientes recurrentes, 70% retención anual, NPS 72, 4.8 en Google (156 reseñas). Revenue: 65K/año creciendo 15% interanual. Equipo: 3 instructores (12, 8 y 6 años experiencia). Fundadora: fisioterapeuta con 15 años en el sector. Advisory board: Dr. López (traumatólogo Hospital Clínico) y Ana Ruiz (ex-directora Holmes Place España).", "efecto": {"persuasion": 0.75, "credibilidad": 0.92, "accion": 0.50, "empatia": 0.15}, "categoria": "pitch_inversor"},
    {"texto": "Con una inversión mínima, el retorno potencial es astronómico. No hay riesgo. El mercado solo sube. Es la oportunidad de tu vida.", "efecto": {"persuasion": 0.30, "credibilidad": 0.02, "accion": 0.35, "empatia": 0.0}, "categoria": "pitch_inversor"},
    {"texto": "Riesgos y mitigaciones: 1) Dependencia de instructores clave → formación interna + salarios competitivos (25% sobre mercado). 2) Estacionalidad verano (-20% clientes) → bonos de verano con descuento + clases al aire libre. 3) Nuevo competidor → barrera de entrada = comunidad (NPS 72, boca-oreja = 62% de leads). 4) Aumento alquiler → contrato 5 años con tope revisión del 3%.", "efecto": {"persuasion": 0.70, "credibilidad": 0.92, "accion": 0.45, "empatia": 0.12}, "categoria": "pitch_inversor"},
    {"texto": "Nuestro TAM es de 2 billones de dólares globalmente. Vamos a capturar el 0.01% que son 200 millones. Solo necesitamos 500K de seed para demostrar el modelo.", "efecto": {"persuasion": 0.20, "credibilidad": 0.05, "accion": 0.15, "empatia": 0.0}, "categoria": "pitch_inversor"},

    # --- propuesta_valor (6) ---
    {"texto": "¿Por qué Estudio Movimiento y no un gimnasio? 1) Máximo 8 personas por clase (en gym son 20-30). 2) Tu instructor sabe tu nombre y tu historial. 3) Adaptamos cada ejercicio a ti (en gym sigues al grupo). 4) Si no vienes, te llamamos (en gym nadie nota tu ausencia). Coste: 30€ más al mes que un gym. Valor: incomparable.", "efecto": {"persuasion": 0.82, "credibilidad": 0.80, "accion": 0.55, "empatia": 0.60}, "categoria": "propuesta_valor"},
    {"texto": "Ofrecemos servicios de alta calidad con un enfoque centrado en el cliente que nos diferencia de la competencia y nos posiciona como líderes del sector.", "efecto": {"persuasion": 0.05, "credibilidad": 0.03, "accion": 0.02, "empatia": 0.02}, "categoria": "propuesta_valor"},
    {"texto": "Pilates terapéutico: lo que nos diferencia es que cada programa empieza con una valoración de 45 minutos donde evaluamos tu movilidad, fuerza y patrones de movimiento. Luego diseñamos un plan de 12 semanas con objetivos medibles. Al mes te reevaluamos y ajustamos. No es 'ven a clase y haz lo que puedas': es un tratamiento con seguimiento.", "efecto": {"persuasion": 0.78, "credibilidad": 0.90, "accion": 0.55, "empatia": 0.50}, "categoria": "propuesta_valor"},
    {"texto": "Somos únicos, diferentes e innovadores. Nuestra metodología exclusiva no se parece a nada que hayas experimentado antes.", "efecto": {"persuasion": 0.10, "credibilidad": 0.02, "accion": 0.08, "empatia": 0.03}, "categoria": "propuesta_valor"},
    {"texto": "Tres compromisos que nos definen: 1) Si después de tu primera clase no te convence, te devolvemos el dinero (hemos devuelto 3 veces en 7 años). 2) Si un instructor no te gusta, te cambiamos de grupo sin preguntas. 3) Si en 3 meses no notas mejora, revisamos tu caso con nuestro fisio de referencia gratis.", "efecto": {"persuasion": 0.80, "credibilidad": 0.88, "accion": 0.60, "empatia": 0.55}, "categoria": "propuesta_valor"},
    {"texto": "Nuestra propuesta integral de bienestar holístico combina lo mejor de la tradición con la vanguardia para crear una sinergia transformadora.", "efecto": {"persuasion": 0.05, "credibilidad": 0.02, "accion": 0.02, "empatia": 0.0}, "categoria": "propuesta_valor"},

    # --- caso_exito (8) ---
    {"texto": "Roberto, 54 años, oficinista. Llegó con dolor lumbar crónico (escala dolor: 7/10), sentado 9h/día. Plan: 2 sesiones Pilates/semana + 15 min ejercicios diarios en casa. Mes 1: dolor baja a 5/10. Mes 3: dolor 3/10, empieza a correr. Mes 6: dolor 1/10, corre 5K tres veces por semana. Coste total: 714€ (6 meses plan Estándar). Alternativa médica que le ofrecían: infiltraciones (200€/sesión, 6 sesiones) + posible cirugía.", "efecto": {"persuasion": 0.82, "credibilidad": 0.92, "accion": 0.50, "empatia": 0.65}, "categoria": "caso_exito"},
    {"texto": "¡Nuestros clientes nos adoran! ¡Las opiniones hablan por sí solas! ¡Ven y compruébalo tú mismo!", "efecto": {"persuasion": 0.10, "credibilidad": 0.02, "accion": 0.15, "empatia": 0.05}, "categoria": "caso_exito"},
    {"texto": "Ana, 38 años, madre de 2 niños, diástasis abdominal post-parto (3 cm separación). Su ginecóloga le recomendó cirugía. Antes quiso probar Pilates. 4 meses de trabajo específico de transverso + hipopresivos (3 sesiones/semana). Resultado: diástasis reducida a 1.2 cm, funcionalidad recuperada, cirugía descartada. Su ginecóloga ahora nos deriva pacientes.", "efecto": {"persuasion": 0.80, "credibilidad": 0.90, "accion": 0.45, "empatia": 0.75}, "categoria": "caso_exito"},
    {"texto": "Todos nuestros clientes están satisfechos. Los resultados hablan por sí solos. La calidad de nuestro servicio es incomparable.", "efecto": {"persuasion": 0.08, "credibilidad": 0.03, "accion": 0.05, "empatia": 0.05}, "categoria": "caso_exito"},
    {"texto": "Empresa TechSolutions (28 empleados): implementaron Pilates corporativo 1 vez/semana. Resultados tras 6 meses: absentismo por dolor de espalda bajó un 45% (de 22 días/trimestre a 12), satisfacción laboral subió 18 puntos en encuesta interna, el 85% de participantes pidió añadir segunda sesión semanal. Coste: 180€/semana. Ahorro estimado en absentismo: 3.200€/trimestre.", "efecto": {"persuasion": 0.82, "credibilidad": 0.92, "accion": 0.55, "empatia": 0.30}, "categoria": "caso_exito"},
    {"texto": "Carmen, 72 años. Empezó Pilates a los 70. Su médico le dijo que la osteoporosis limitaría su movilidad progresivamente. 2 años después: densitometría mejoró un 4%, no ha tenido caídas (antes 2-3 al año), y se va de viaje con sus amigas sin bastón. Viene los martes y jueves con su grupo de 'jubiladas guerreras' (su nombre, no el nuestro).", "efecto": {"persuasion": 0.75, "credibilidad": 0.88, "accion": 0.35, "empatia": 0.90}, "categoria": "caso_exito"},
    {"texto": "Miguel, autónomo, estrés alto, insomnio. Empezó Pilates 'porque su novia le obligó'. A las 3 semanas estaba dormido antes que ella. A los 2 meses dejó el ansiolítico (con supervisión médica). No es magia: el ejercicio regulado + la respiración consciente regulan el sistema nervioso. Él mismo lo dice: 'Es la mejor inversión que he hecho'.", "efecto": {"persuasion": 0.78, "credibilidad": 0.80, "accion": 0.35, "empatia": 0.82}, "categoria": "caso_exito"},
    {"texto": "Testimonio verificable: llama a cualquiera de nuestros clientes. Te damos 5 nombres y teléfonos (con su permiso) para que les preguntes directamente. Ningún estudio de la zona hace esto.", "efecto": {"persuasion": 0.75, "credibilidad": 0.90, "accion": 0.65, "empatia": 0.40}, "categoria": "caso_exito"},

    # --- objecion_respuesta (8) ---
    {"texto": "'Es caro.' Entiendo. Hagamos números: 119€/mes entre 12 clases son 9,90€ por clase de 50 minutos con instructor personal y máximo 8 personas. Una sesión de fisio son 45-60€. Un mes de gym con monitor son 40-50€ pero las clases son de 20 personas y nadie te corrige. ¿Qué te da más valor?", "efecto": {"persuasion": 0.82, "credibilidad": 0.88, "accion": 0.60, "empatia": 0.50}, "categoria": "objecion_respuesta"},
    {"texto": "No te preocupes por el precio, la salud no tiene precio. Invertir en ti siempre merece la pena.", "efecto": {"persuasion": 0.15, "credibilidad": 0.05, "accion": 0.08, "empatia": 0.20}, "categoria": "objecion_respuesta"},
    {"texto": "'No tengo tiempo.' Lo entiendo, todos vamos justos. Tenemos clases de 7:30 a 20:30. Con 2 sesiones de 50 minutos a la semana es suficiente. Son menos de 2 horas semanales. ¿Cuántas horas a la semana pasas con dolor de espalda sin hacer nada productivo? Te propongo: prueba un mes con 2 clases/semana y mide si tu dolor mejora.", "efecto": {"persuasion": 0.80, "credibilidad": 0.78, "accion": 0.75, "empatia": 0.60}, "categoria": "objecion_respuesta"},
    {"texto": "'No soy flexible.' Perfecto, esa es exactamente la razón para empezar. El Pilates no requiere flexibilidad, la desarrolla. El 70% de nuestros clientes empezaron sin poder tocarse las rodillas. Laura (tu monitora) adapta cada ejercicio a tu nivel. Literalmente nadie en la clase hace el mismo ejercicio exactamente igual.", "efecto": {"persuasion": 0.78, "credibilidad": 0.82, "accion": 0.55, "empatia": 0.65}, "categoria": "objecion_respuesta"},
    {"texto": "Bueno, piénsalo y cuando te decidas nos llamas. Aquí estaremos.", "efecto": {"persuasion": 0.05, "credibilidad": 0.10, "accion": 0.02, "empatia": 0.15}, "categoria": "objecion_respuesta"},
    {"texto": "'Ya hago yoga.' Genial, el yoga y el Pilates se complementan bien. El yoga trabaja más la flexibilidad y la calma. El Pilates trabaja más el control, la estabilización y la fuerza del core. Tenemos 4 clientes que hacen ambos y dicen que el Pilates les ha mejorado las posturas de yoga. ¿Quieres probar una clase gratis y comparar?", "efecto": {"persuasion": 0.75, "credibilidad": 0.82, "accion": 0.72, "empatia": 0.55}, "categoria": "objecion_respuesta"},
    {"texto": "'Estoy lesionado.' Precisamente por eso. El Pilates terapéutico está diseñado para rehabilitación. Necesitamos el informe de tu médico o fisio, y adaptamos todo. Tenemos experiencia con: hernias discales (14 clientes), prótesis de rodilla (6), post-operatorio de hombro (8). ¿Cuál es tu caso? Puedo hablar con tu médico si quieres.", "efecto": {"persuasion": 0.82, "credibilidad": 0.90, "accion": 0.72, "empatia": 0.70}, "categoria": "objecion_respuesta"},
    {"texto": "No tienes excusas. Todo el mundo puede hacer Pilates. Solo necesitas querer hacerlo. ¿A qué esperas?", "efecto": {"persuasion": 0.20, "credibilidad": 0.05, "accion": 0.30, "empatia": 0.0}, "categoria": "objecion_respuesta"},

    # =====================================================================
    # POLITICA / PUBLICO (15 textos)
    # =====================================================================

    # --- discurso_politico (6) ---
    {"texto": "En los últimos 4 años, hemos construido 12 centros deportivos municipales, beneficiando a 45.000 vecinos. El presupuesto deportivo pasó de 2.3M a 4.1M€. La tasa de sedentarismo en el municipio bajó del 62% al 48%. Quedan desafíos: la zona sur sigue sin instalaciones. Nuestro plan: 3 centros más en 2027, con especial atención a barrios con menor renta.", "efecto": {"persuasion": 0.70, "credibilidad": 0.88, "accion": 0.50, "empatia": 0.40}, "categoria": "discurso_politico"},
    {"texto": "Nuestros adversarios quieren destruir todo lo que hemos construido. Solo nosotros podemos salvar esta ciudad. O estáis con nosotros o estáis contra el progreso. La elección es clara.", "efecto": {"persuasion": 0.50, "credibilidad": 0.05, "accion": 0.40, "empatia": 0.10}, "categoria": "discurso_politico"},
    {"texto": "El programa de becas deportivas alcanzó a 230 jóvenes de familias con ingresos inferiores a 15.000€/año. De ellos, 12 compiten ya a nivel nacional. No son números: son María del barrio de La Paz que entrena natación a las 6 de la mañana, o Alejandro de Los Rosales que representa a España en atletismo sub-18. Cada euro invertido en deporte base evita 4€ en problemas sociales.", "efecto": {"persuasion": 0.78, "credibilidad": 0.85, "accion": 0.42, "empatia": 0.80}, "categoria": "discurso_politico"},
    {"texto": "Vamos a hacer de esta ciudad la mejor del país. Vamos a crear millones de empleos. Va a ser increíble, lo mejor que habéis visto. Nadie va a hacer esto mejor que nosotros. Créanme.", "efecto": {"persuasion": 0.35, "credibilidad": 0.03, "accion": 0.20, "empatia": 0.08}, "categoria": "discurso_politico"},
    {"texto": "Seré honesto: prometimos 5 parques y solo hemos entregado 3. Los otros 2 se retrasaron por problemas con la licitación. No es excusa, es un hecho. Para que no vuelva a pasar, hemos cambiado el proceso de contratación y los 2 parques pendientes estarán terminados en septiembre. Podéis seguir el avance en la web de transparencia.", "efecto": {"persuasion": 0.72, "credibilidad": 0.88, "accion": 0.45, "empatia": 0.55}, "categoria": "discurso_politico"},
    {"texto": "Todos sabemos que el otro partido miente. Siempre mienten. Es lo que hacen. Nosotros somos los únicos honestos. Los únicos que trabajan de verdad por el pueblo.", "efecto": {"persuasion": 0.40, "credibilidad": 0.03, "accion": 0.25, "empatia": 0.08}, "categoria": "discurso_politico"},

    # --- comunicado_crisis (5) ---
    {"texto": "Ayer a las 14:30 una clienta (62 años) sufrió un mareo durante clase. Actuamos según protocolo: instructor detuvo la clase, pidió ayuda, se llamó al 112. La ambulancia llegó en 8 minutos. Diagnóstico: hipotensión por deshidratación. La clienta está bien, fue dada de alta a las 19:00. Acciones tomadas: revisamos protocolo de hidratación, a partir de hoy recordamos beber agua al inicio de cada clase, y tenemos tensiómetro en recepción.", "efecto": {"persuasion": 0.50, "credibilidad": 0.92, "accion": 0.62, "empatia": 0.68}, "categoria": "comunicado_crisis"},
    {"texto": "Lamentamos profundamente los inconvenientes causados. Estamos trabajando incansablemente para resolver la situación. Les mantendremos informados.", "efecto": {"persuasion": 0.08, "credibilidad": 0.08, "accion": 0.05, "empatia": 0.15}, "categoria": "comunicado_crisis"},
    {"texto": "Informamos que mañana lunes 4 de marzo el estudio permanecerá cerrado por avería en la calefacción. El técnico viene mañana a primera hora. Previsión: resolver en el día. Si no se resuelve mañana, martes abrimos con radiadores portátiles (sala a 20°C mínimo). Todas las clases de mañana se recuperan: Laura os contactará hoy para reagendar. Disculpad las molestias.", "efecto": {"persuasion": 0.40, "credibilidad": 0.88, "accion": 0.75, "empatia": 0.50}, "categoria": "comunicado_crisis"},
    {"texto": "Transparencia total: el mes pasado tuvimos una inspección de Sanidad. Resultado: 2 observaciones menores (faltaba el registro de temperatura de la sala y un extintor estaba caducado). Ambas corregidas el mismo día. Próxima inspección: voluntaria, la hemos solicitado nosotros para agosto. El acta está disponible en recepción para quien quiera verla.", "efecto": {"persuasion": 0.55, "credibilidad": 0.92, "accion": 0.35, "empatia": 0.40}, "categoria": "comunicado_crisis"},
    {"texto": "Debido a circunstancias imprevistas e inevitables fuera de nuestro control, nos vemos en la obligación de comunicar ciertos ajustes temporales que podrían afectar a la prestación normal del servicio.", "efecto": {"persuasion": 0.05, "credibilidad": 0.05, "accion": 0.05, "empatia": 0.03}, "categoria": "comunicado_crisis"},

    # --- opinion_editorial (4) ---
    {"texto": "El sector del fitness en España factura 2.700M€/año, pero el 80% de la población sigue siendo sedentaria. Los gimnasios venden acceso, no resultados. El modelo de estudio boutique (Pilates, yoga, CrossFit) está creciendo un 15% anual porque ofrece algo que el gym no puede: comunidad, personalización y accountability. El futuro del fitness no es más grande, es más pequeño.", "efecto": {"persuasion": 0.72, "credibilidad": 0.82, "accion": 0.25, "empatia": 0.30}, "categoria": "opinion_editorial"},
    {"texto": "El Pilates es maravilloso y todo el mundo debería practicarlo. Es la mejor forma de ejercicio que existe. Punto.", "efecto": {"persuasion": 0.10, "credibilidad": 0.02, "accion": 0.08, "empatia": 0.05}, "categoria": "opinion_editorial"},
    {"texto": "Hay un problema que nadie habla: la mayoría de instructores de Pilates en España cobran 10-15€/hora como autónomos. Eso es insostenible. Si queremos profesionales cualificados que cuiden bien a los clientes, tenemos que pagar mejor. En nuestro estudio pagamos 22€/hora y el resultado es que llevamos 4 años sin rotación. El coste de reemplazar un instructor es 3 veces su salario mensual.", "efecto": {"persuasion": 0.70, "credibilidad": 0.85, "accion": 0.30, "empatia": 0.60}, "categoria": "opinion_editorial"},
    {"texto": "La sociedad moderna está enferma. La gente no se mueve, come mal y está estresada. Necesitamos una revolución del bienestar. Necesitamos volver a lo natural. Necesitamos despertar.", "efecto": {"persuasion": 0.25, "credibilidad": 0.05, "accion": 0.15, "empatia": 0.15}, "categoria": "opinion_editorial"},

    # =====================================================================
    # TERAPIA / COACHING (15 textos)
    # =====================================================================

    # --- intervencion_terapeutica (8) ---
    {"texto": "Dices que 'siempre' te sientes así. ¿Puedes recordar un momento concreto de la última semana en que no te sentiste así? Aunque fuera breve. A veces un 'siempre' esconde excepciones que nos dan pistas.", "efecto": {"persuasion": 0.55, "credibilidad": 0.72, "accion": 0.40, "empatia": 0.85}, "categoria": "intervencion_terapeutica"},
    {"texto": "Lo que necesitas es ser más positivo. Piensa en lo bueno que tienes. Hay gente que está mucho peor que tú. Tienes que ser fuerte.", "efecto": {"persuasion": 0.10, "credibilidad": 0.05, "accion": 0.08, "empatia": 0.0}, "categoria": "intervencion_terapeutica"},
    {"texto": "Noto que cuando hablas de tu madre, tu cuerpo se tensa. Los hombros suben, aprietas las manos. ¿Qué está pasando ahí? No tienes que responder ahora si no quieres. Solo quiero que lo notes.", "efecto": {"persuasion": 0.45, "credibilidad": 0.78, "accion": 0.35, "empatia": 0.92}, "categoria": "intervencion_terapeutica"},
    {"texto": "Has dicho dos cosas interesantes: que quieres cambiar de trabajo y que te da miedo el cambio. Las dos son verdad al mismo tiempo. No tienes que elegir entre ellas ahora. ¿Qué pasaría si las dos pudieran coexistir un rato?", "efecto": {"persuasion": 0.50, "credibilidad": 0.75, "accion": 0.30, "empatia": 0.88}, "categoria": "intervencion_terapeutica"},
    {"texto": "Tienes que dejar de preocuparte tanto. El estrés no es bueno. Relájate y las cosas se solucionarán solas. Todo pasa por algo.", "efecto": {"persuasion": 0.08, "credibilidad": 0.03, "accion": 0.05, "empatia": 0.05}, "categoria": "intervencion_terapeutica"},
    {"texto": "Vamos a hacer una pausa. Respira. Estás hablando muy rápido y noto que la emoción está subiendo. No pasa nada. Tómate un momento. Estoy aquí. Cuando estés lista, seguimos. O no. Lo que necesites.", "efecto": {"persuasion": 0.30, "credibilidad": 0.70, "accion": 0.45, "empatia": 0.95}, "categoria": "intervencion_terapeutica"},
    {"texto": "La semana pasada dijiste que querías poner límites con tu jefe. ¿Qué ha pasado desde entonces? ¿Hubo algún momento en que pudiste hacerlo? ¿Cómo fue? Si no pudiste, ¿qué se interpuso?", "efecto": {"persuasion": 0.45, "credibilidad": 0.78, "accion": 0.60, "empatia": 0.72}, "categoria": "intervencion_terapeutica"},
    {"texto": "Lo que me cuentas es duro. Tiene sentido que te sientas así. Cualquiera en tu situación se sentiría abrumado. No estás exagerando. Dicho esto, me pregunto si hay algo pequeño, muy pequeño, que puedas hacer esta semana que te devuelva un poquito de control. No resolver todo. Solo algo.", "efecto": {"persuasion": 0.55, "credibilidad": 0.75, "accion": 0.55, "empatia": 0.92}, "categoria": "intervencion_terapeutica"},

    # --- coaching_sesion (7) ---
    {"texto": "En una escala del 1 al 10, ¿cuánto de satisfecho estás con tu situación actual? ¿Y qué tendría que pasar para subir un punto? Solo uno.", "efecto": {"persuasion": 0.50, "credibilidad": 0.70, "accion": 0.65, "empatia": 0.60}, "categoria": "coaching_sesion"},
    {"texto": "¡Tienes que creer en ti! ¡Eres increíble! ¡Puedes con todo! ¡El universo conspira a tu favor! ¡Solo tienes que visualizarlo!", "efecto": {"persuasion": 0.15, "credibilidad": 0.02, "accion": 0.10, "empatia": 0.10}, "categoria": "coaching_sesion"},
    {"texto": "Llevas 3 sesiones hablando de cambiar de trabajo pero no has hecho nada concreto. No es un juicio, es una observación. ¿Qué crees que está pasando? ¿Es que realmente no quieres cambiarlo, o hay algo que te frena y no hemos identificado?", "efecto": {"persuasion": 0.60, "credibilidad": 0.80, "accion": 0.55, "empatia": 0.65}, "categoria": "coaching_sesion"},
    {"texto": "Vamos a definir tu objetivo para el próximo mes. Tiene que ser: específico (qué exactamente), medible (cómo sabrás que lo has logrado), con fecha (para cuándo) y que dependa de ti (no de otros). ¿Cuál sería?", "efecto": {"persuasion": 0.45, "credibilidad": 0.82, "accion": 0.88, "empatia": 0.40}, "categoria": "coaching_sesion"},
    {"texto": "Simplemente necesitas más motivación. Lee libros de autoayuda, escucha podcasts positivos y rodéate de gente que te inspire. Verás cómo todo cambia.", "efecto": {"persuasion": 0.12, "credibilidad": 0.05, "accion": 0.15, "empatia": 0.08}, "categoria": "coaching_sesion"},
    {"texto": "Me dices que quieres emprender pero tienes miedo. ¿Qué es lo peor que puede pasar realmente? No en tu cabeza, sino en la realidad. Si fracasas, ¿qué pierdes concretamente? Y si no lo intentas, ¿qué pierdes? A veces el mayor riesgo es no hacer nada.", "efecto": {"persuasion": 0.72, "credibilidad": 0.75, "accion": 0.60, "empatia": 0.70}, "categoria": "coaching_sesion"},
    {"texto": "Tu tarea para esta semana: una conversación de 15 minutos con alguien que haya hecho lo que tú quieres hacer. No pedir consejo, solo escuchar su experiencia. ¿A quién podrías contactar? ¿Cuándo? Escríbelo ahora y mándame un WhatsApp cuando lo hayas hecho.", "efecto": {"persuasion": 0.55, "credibilidad": 0.78, "accion": 0.92, "empatia": 0.50}, "categoria": "coaching_sesion"},
]
